import os
import json

# --- CONFIGURATION ---
IMAGE_FOLDER_PATH = './images/stickers'  # Folder with your cutout cat images
WEB_PATH_PREFIX = './images/stickers/'   # Path used in the HTML src=""
VALID_EXTENSIONS = ('.jpg', '.jpeg', '.png', '.webp')

def generate_random_orbit_html():
    try:
        # 1. GET FILES
        files = sorted([f for f in os.listdir(IMAGE_FOLDER_PATH) 
                        if f.lower().endswith(VALID_EXTENSIONS)])
        
        if not files:
            print(f"No images found in {IMAGE_FOLDER_PATH}")
            return

        # 2. CREATE JS ARRAY
        # We format the list of files into a JavaScript array string
        # e.g. ["./images/stickers/cat1.png", "./images/stickers/cat2.png"]
        js_file_list = [f"{WEB_PATH_PREFIX}{filename}" for filename in files]
        js_array_string = json.dumps(js_file_list, indent=4)

        # 3. GENERATE HTML
        # This is the template with the 3 rings and the JS block
        html_template = f"""
<!-- ============================================ -->
<!-- HERO SECTION (3 Random Orbiting Cats) -->
<!-- ============================================ -->
<section id="hero" class="relative flex min-h-screen w-full flex-col items-center justify-center overflow-hidden bg-[#4A6C9B] pt-20">

    <!-- 🌌 ORBIT CONTAINER -->
    <div class="absolute inset-0 flex items-center justify-center pointer-events-none">
        
        <!-- RING 1: INNER (Smallest) -->
        <div class="absolute rounded-full border border-white/5 opacity-80
                    w-[360px] h-[360px] md:w-[900px] md:h-[900px]"
             style="animation: orbit-cw 30s linear infinite; animation-delay: -5s;">
            <div class="absolute -top-10 left-1/2 -translate-x-1/2 w-28 md:w-40"
                 style="animation: orbit-ccw 30s linear infinite; animation-delay: -5s;"> 
                <img id="ring1-img" src="" class="w-full drop-shadow-2xl transform hover:scale-110 transition-transform duration-300 hidden" alt="Random Cat 1">
            </div>
        </div>

        <!-- RING 2: MIDDLE -->
        <div class="absolute rounded-full border border-white/5 opacity-80
                    w-[500px] h-[500px] md:w-[1150px] md:h-[1150px]"
             style="animation: orbit-cw 45s linear infinite reverse; animation-delay: -20s;"> 
            <div class="absolute top-1/2 -left-10 -translate-y-1/2 w-32 md:w-44"
                 style="animation: orbit-ccw 45s linear infinite reverse; animation-delay: -20s;">
                <img id="ring2-img" src="" class="w-full drop-shadow-2xl transform hover:scale-110 transition-transform duration-300 hidden" alt="Random Cat 2">
            </div>
        </div>

        <!-- RING 3: OUTER (Largest) -->
        <div class="absolute rounded-full border border-white/5 opacity-80
                    w-[650px] h-[650px] md:w-[1400px] md:h-[1400px]"
             style="animation: orbit-cw 60s linear infinite; animation-delay: -10s;">
            <div class="absolute bottom-20 right-20 w-36 md:w-48"
                 style="animation: orbit-ccw 60s linear infinite; animation-delay: -10s;">
                <img id="ring3-img" src="" class="w-full drop-shadow-2xl transform hover:scale-110 transition-transform duration-300 hidden" alt="Random Cat 3">
            </div>
        </div>
    </div>

    <!-- MAIN TEXT -->
    <div class="z-20 flex flex-col gap-4 text-center px-4 relative">
        <h1 class="text-white text-6xl md:text-8xl lg:text-9xl font-display font-bold leading-tight drop-shadow-lg animate-fade-in-up">
            Abigail & Rathin
        </h1>
        <h2 class="text-white text-lg md:text-2xl font-normal leading-normal tracking-wide drop-shadow-md animate-fade-in-up" style="animation-delay: 0.1s;">
            August 15, 2026 | Dundas, Minnesota
        </h2>
    </div>

    <a href="#rsvp" class="z-30 mt-8 flex min-w-[160px] cursor-pointer items-center justify-center rounded-full h-14 px-8 bg-accent text-background text-lg font-bold tracking-wide hover:bg-white hover:scale-105 transition-all duration-300 shadow-lg animate-fade-in-up" style="animation-delay: 0.2s;">
        RSVP opens on March 1st!
    </a>

    <!-- 🎲 RANDOM CAT SCRIPT -->
    <script>
        document.addEventListener("DOMContentLoaded", () => {{
            // 1. POOL OF IMAGES (Generated by Python)
            const stickerImages = {js_array_string};

            // 2. SHUFFLE & SELECT 3
            const shuffled = stickerImages.sort(() => 0.5 - Math.random());
            const selected = shuffled.slice(0, 3); 

            // 3. ASSIGN TO RINGS
            const img1 = document.getElementById('ring1-img');
            const img2 = document.getElementById('ring2-img');
            const img3 = document.getElementById('ring3-img');

            if (selected[0]) {{ img1.src = selected[0]; img1.classList.remove('hidden'); }}
            if (selected[1]) {{ img2.src = selected[1]; img2.classList.remove('hidden'); }}
            if (selected[2]) {{ img3.src = selected[2]; img3.classList.remove('hidden'); }}
        }});
    </script>
</section>
"""
        print(f"Found {len(files)} images. Copy the code below:\n")
        print("-" * 60)
        print(html_template)
        print("-" * 60)

    except FileNotFoundError:
        print(f"Error: The folder '{IMAGE_FOLDER_PATH}' was not found.")

if __name__ == "__main__":
    generate_random_orbit_html()